from graphics import *
from math import *
def main():
        r = 500
        d = 2*r
        awx = Point(r,0)
        akx = Point(r,d)
        awy = Point(0,r)
        aky = Point(d,r)
        win = GraphWin("PIR-Pattern", d, d)
        radius = 0.25 * r
        center = Point(r, r)
        s = 10,20,30,40,50,60,70,80
        a0 = Entry(Point(220,70),5)
        a0.setText("0.0")
        a0.draw(win)
        a1 = Entry(Point(220,90),5)
        a1.setText("0.0")
        a1.draw(win)
        a2 = Entry(Point(220,110),5)
        a2.setText("0.0")
        a2.draw(win)
        a3 = Entry(Point(220,130),5)
        a3.setText("0.0")
        a3.draw(win)
        a4 = Entry(Point(220,150),5)
        a4.setText("0.0")
        a4.draw(win)
        a5 = Entry(Point(220,170),5)
        a5.setText("0.0")
        a5.draw(win)
        a6 = Entry(Point(220,190),5)
        a6.setText("0.0")
        a6.draw(win)
        a7 = Entry(Point(220,210),5)
        a7.setText("0.0")
        a7.draw(win)
        a8 = Entry(Point(220,230),5)
        a8.setText("0.0")
        a8.draw(win)
        area = [(4, 'white'), (3, 'white'), (2, 'white'), (1, 'white')]
        wj = 'white'
        w = 'red','magenta','orange','yellow','green','cyan','blue','violet','purple'
        for faktor, warna in area:
            lingkaran = Circle(center, radius * faktor)
            lingkaran.setFill('black')
            lingkaran.setOutline(warna)
            lingkaran.draw(win)    
        ket0 = Text(Point(100,50),'Line Color Info')
        ket0.setTextColor(wj)
        ket0.setSize(16)
        ket0.setStyle('bold')
        ket0.draw(win)
        ket1 = Text(Point(220,50),'-Jarak(m)')
        ket1.setTextColor(wj)
        ket1.setSize(16)
        ket1.setStyle('bold')
        ket1.draw(win)
        ket0 = Text(Point(100,70),'---  0(degree)')
        ket0.setTextColor(w[0])
        ket0.setSize(12)
        ket0.setStyle('bold')
        ket0.draw(win)
        ket1 = Text(Point(100,90),'--- 10(degree)')
        ket1.setTextColor(w[1])
        ket1.setSize(12)
        ket1.setStyle('bold')
        ket1.draw(win)
        ket2 = Text(Point(100,110),'--- 20(degree)')
        ket2.setTextColor(w[2])
        ket2.setSize(12)
        ket2.setStyle('bold')
        ket2.draw(win)
        ket3 = Text(Point(100,130),'--- 30(degree)')
        ket3.setTextColor(w[3])
        ket3.setSize(12)
        ket3.setStyle('bold')
        ket3.draw(win)
        ket4 = Text(Point(100,150),'--- 40(degree)')
        ket4.setTextColor(w[4])
        ket4.setSize(12)
        ket4.setStyle('bold')
        ket4.draw(win)
        ket5 = Text(Point(100,170),'--- 50(degree)')
        ket5.setTextColor(w[5])
        ket5.setSize(12)
        ket5.setStyle('bold')
        ket5.draw(win)
        ket6 = Text(Point(100,190),'--- 60(degree)')
        ket6.setTextColor(w[6])
        ket6.setSize(12)
        ket6.setStyle('bold')
        ket6.draw(win)
        ket7 = Text(Point(100,210),'--- 70(degree)')
        ket7.setTextColor(w[7])
        ket7.setSize(12)
        ket7.setStyle('bold')
        ket7.draw(win)
        ket8 = Text(Point(100,230),'--- 80(degree)')
        ket8.setTextColor(w[8])
        ket8.setSize(12)
        ket8.setStyle('bold')
        ket8.draw(win)
        dr = Text(Point(100,270),'DRAW')
        dr.setTextColor(wj)
        dr.setSize(16)
        dr.setStyle('bold')
        dr.draw(win)
        ex = Text(Point(100,320),'EXIT')
        ex.setTextColor(wj)
        ex.setSize(16)
        ex.setStyle('bold')
        ex.draw(win)
        win.getMouse()
        a0 = eval(a0.getText())
        a1 = eval(a1.getText())
        a2 = eval(a2.getText())
        a3 = eval(a3.getText())
        a4 = eval(a4.getText())
        a5 = eval(a5.getText())
        a6 = eval(a6.getText())
        a7 = eval(a7.getText())
        a8 = eval(a8.getText())
        sb1 = Line(awx, akx)
        sb1.setOutline(wj)
        sb1.draw(win)
        sb2 = Line(awy, center)
        sb2.setOutline(wj)
        sb2.draw(win)
        sb3 = Line(center, aky)
        sb3.setOutline(wj)
        sb3.draw(win)
        t0 = r+(a0*100)
        sb0 = Line(center, Point(t0,r))
        sb0.setOutline(w[0])
        sb0.draw(win)
        def pola(a,b):
            x = a*100
            z = sqrt(2*x*x*(1-(cos(radians(b)))))
            y1 = r - z
            y2 = r + z
            return x, y1, y2
        g1 = pola(a1,s[0])
        g2 = pola(a2,s[1])
        g3 = pola(a3,s[2])
        g4 = pola(a4,s[3])
        g5 = pola(a5,s[4])
        g6 = pola(a6,s[5])
        g7 = pola(a7,s[6])
        g8 = pola(a8,s[7])
        #10 derajat
        h1a = Line(center, Point(g1[0]+r, g1[1]))
        h1b = Line(center, Point(g1[0]+r, g1[2]))
        h1ax1 = Line(Point(g1[0]+r, g1[1]), Point(t0,r))
        h1ax2 = Line(Point(g1[0]+r, g1[2]), Point(t0,r))
        h1ay1 = Line(Point(g1[0]+r, g1[1]), Point(g1[0]+r,r))
        h1ay2 = Line(Point(g1[0]+r, g1[2]), Point(g1[0]+r,r))
        h1a.setOutline(w[1])
        h1a.draw(win)
        h1b.setOutline(w[1])
        h1b.draw(win)
        h1ax1.setOutline(wj)
        h1ax1.draw(win)
        h1ax2.setOutline(wj)
        h1ax2.draw(win)
        h1ay1.setOutline(w[1])
        h1ay1.draw(win)
        h1ay2.setOutline(w[1])
        h1ay2.draw(win)
        #20 derajat
        h2a = Line(center, Point(g2[0]+r, g2[1]))
        h2b = Line(center, Point(g2[0]+r, g2[2]))
        h2ax1 = Line(Point(g2[0]+r, g2[1]), Point(g1[0]+r, g1[1]))
        h2ax2 = Line(Point(g2[0]+r, g2[2]), Point(g1[0]+r, g1[2]))
        h2ay1 = Line(Point(g2[0]+r, g2[1]), Point(g2[0]+r,r))
        h2ay2 = Line(Point(g2[0]+r, g2[2]), Point(g2[0]+r,r))
        h2a.setOutline(w[2])
        h2a.draw(win)
        h2b.setOutline(w[2])
        h2b.draw(win)
        h2ax1.setOutline(wj)
        h2ax1.draw(win)
        h2ax2.setOutline(wj)
        h2ax2.draw(win)
        h2ay1.setOutline(w[2])
        h2ay1.draw(win)
        h2ay2.setOutline(w[2])
        h2ay2.draw(win)
        #30 derajat
        h3a = Line(center, Point(g3[0]+r, g3[1]))
        h3b = Line(center, Point(g3[0]+r, g3[2]))
        h3ax1 = Line(Point(g3[0]+r, g3[1]), Point(g2[0]+r, g2[1]))
        h3ax2 = Line(Point(g3[0]+r, g3[2]), Point(g2[0]+r, g2[2]))
        h3ay1 = Line(Point(g3[0]+r, g3[1]), Point(g3[0]+r,r))
        h3ay2 = Line(Point(g3[0]+r, g3[2]), Point(g3[0]+r,r))
        h3a.setOutline(w[3])
        h3a.draw(win)
        h3b.setOutline(w[3])
        h3b.draw(win)
        h3ax1.setOutline(wj)
        h3ax1.draw(win)
        h3ax2.setOutline(wj)
        h3ax2.draw(win)
        h3ay1.setOutline(w[3])
        h3ay1.draw(win)
        h3ay2.setOutline(w[3])
        h3ay2.draw(win)
        #40 derajat
        h4a = Line(center, Point(g4[0]+r, g4[1]))
        h4b = Line(center, Point(g4[0]+r, g4[2]))
        h4ax1 = Line(Point(g4[0]+r, g4[1]), Point(g3[0]+r, g3[1]))
        h4ax2 = Line(Point(g4[0]+r, g4[2]), Point(g3[0]+r, g3[2]))
        h4ay1 = Line(Point(g4[0]+r, g4[1]), Point(g4[0]+r,r))
        h4ay2 = Line(Point(g4[0]+r, g4[2]), Point(g4[0]+r,r))
        h4a.setOutline(w[4])
        h4a.draw(win)
        h4b.setOutline(w[4])
        h4b.draw(win)
        h4ax1.setOutline(wj)
        h4ax1.draw(win)
        h4ax2.setOutline(wj)
        h4ax2.draw(win)
        h4ay1.setOutline(w[4])
        h4ay1.draw(win)
        h4ay2.setOutline(w[4])
        h4ay2.draw(win)
        #50 derajat
        h5a = Line(center, Point(g5[0]+r, g5[1]))
        h5b = Line(center, Point(g5[0]+r, g5[2]))
        h5ax1 = Line(Point(g5[0]+r, g5[1]), Point(g4[0]+r, g4[1]))
        h5ax2 = Line(Point(g5[0]+r, g5[2]), Point(g4[0]+r, g4[2]))
        h5ay1 = Line(Point(g5[0]+r, g5[1]), Point(g5[0]+r,r))
        h5ay2 = Line(Point(g5[0]+r, g5[2]), Point(g5[0]+r,r))
        h5a.setOutline(w[5])
        h5a.draw(win)
        h5b.setOutline(w[5])
        h5b.draw(win)
        h5ax1.setOutline(wj)
        h5ax1.draw(win)
        h5ax2.setOutline(wj)
        h5ax2.draw(win)
        h5ay1.setOutline(w[5])
        h5ay1.draw(win)
        h5ay2.setOutline(w[5])
        h5ay2.draw(win)
        #60 derajat
        h6a = Line(center, Point(g6[0]+r, g6[1]))
        h6b = Line(center, Point(g6[0]+r, g6[2]))
        h6ax1 = Line(Point(g6[0]+r, g6[1]), Point(g5[0]+r, g5[1]))
        h6ax2 = Line(Point(g6[0]+r, g6[2]), Point(g5[0]+r, g5[2]))
        h6ay1 = Line(Point(g6[0]+r, g6[1]), Point(g6[0]+r,r))
        h6ay2 = Line(Point(g6[0]+r, g6[2]), Point(g6[0]+r,r))
        h6a.setOutline(w[6])
        h6a.draw(win)
        h6b.setOutline(w[6])
        h6b.draw(win)
        h6ax1.setOutline(wj)
        h6ax1.draw(win)
        h6ax2.setOutline(wj)
        h6ax2.draw(win)
        h6ay1.setOutline(w[6])
        h6ay1.draw(win)
        h6ay2.setOutline(w[6])
        h6ay2.draw(win)
        #70 derajat
        h7a = Line(center, Point(g7[0]+r, g7[1]))
        h7b = Line(center, Point(g7[0]+r, g7[2]))
        h7ax1 = Line(Point(g7[0]+r, g7[1]), Point(g6[0]+r, g6[1]))
        h7ax2 = Line(Point(g7[0]+r, g7[2]), Point(g6[0]+r, g6[2]))
        h7ay1 = Line(Point(g7[0]+r, g7[1]), Point(g7[0]+r,r))
        h7ay2 = Line(Point(g7[0]+r, g7[2]), Point(g7[0]+r,r))
        h7a.setOutline(w[7])
        h7a.draw(win)
        h7b.setOutline(w[7])
        h7b.draw(win)
        h7ax1.setOutline(wj)
        h7ax1.draw(win)
        h7ax2.setOutline(wj)
        h7ax2.draw(win)
        h7ay1.setOutline(w[7])
        h7ay1.draw(win)
        h7ay2.setOutline(w[7])
        h7ay2.draw(win)
        #80 derajat
        h8a = Line(center, Point(g8[0]+r, g8[1]))
        h8b = Line(center, Point(g8[0]+r, g8[2]))
        h8ax1 = Line(Point(g8[0]+r, g8[1]), Point(g7[0]+r, g7[1]))
        h8ax2 = Line(Point(g8[0]+r, g8[2]), Point(g7[0]+r, g7[2]))
        h8ay1 = Line(Point(g8[0]+r, g8[1]), Point(g8[0]+r,r))
        h8ay2 = Line(Point(g8[0]+r, g8[2]), Point(g8[0]+r,r))
        h8a.setOutline(w[8])
        h8a.draw(win)
        h8b.setOutline(w[8])
        h8b.draw(win)
        h8ax1.setOutline(wj)
        h8ax1.draw(win)
        h8ax2.setOutline(wj)
        h8ax2.draw(win)
        h8ay1.setOutline(w[8])
        h8ay1.draw(win)
        h8ay2.setOutline(w[8])
        h8ay2.draw(win)
        for i in range(10):
            koordinat = win.getMouse()
            jarak = koordinat.getX() - r
            jar = jarak , 'cm'
            koor = Point(koordinat.getX(),koordinat.getY())
            tampilan = Text(koor, jar)
            tampilan.setTextColor('cyan')
            tampilan.setSize(18)
            tampilan.setStyle('bold')
            tampilan.draw(win)
        win.getMouse()
        win.close()
main()